restore:
  file_name: ${file_name}
  bucket_uri: ${bucket_uri}
  database_endpoint: "${db_endpoint}"
  database_password: "${db_password}"
  database_user: "${db_username}"
  provider: "${bucket_provider_type}"

auth:
  username: "${custom_user_username}"

annotations:
  ${annotations}

bucket_provider_type: ${bucket_provider_type}

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"

restorejob:
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 100m
